### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by diomed** [BuddyCSS/BuddyCSS#3]
would be good if you put css file somewhere on cdn or if you already did, to have a link in documentation

**Comment by BuddyCSS** [comment]
I will publish a new release in the middle of the next week with CDN :)

**Comment by BuddyCSS** [comment]
Hey @diomed 

Here are links for CDN

<link rel="stylesheet"type="text/css"href="https://buddycsscc55.kxcdn.com/downloads/1.0.7/css/buddycss.plugins.min.css">

<link rel="stylesheet" type="text/css" href="https://buddycss-cc55.kxcdn.com/downloads/1.0.7/css/buddy.min.css">

<script type="text/javascript" src="https://buddycss-cc55.kxcdn.com/downloads/1.0.7/js/buddy.min.js">

They are also on homepage and readme.md
