### ISSUE TITLE
Opening modal on page loading

### ISSUE THREAD

**Issue by Neofox** [BuddyCSS/BuddyCSS#8]
Hello, I would like to open a modal when the page load but there isn't any way to do it.
I'll love something like that `$('.modal').show()` like bootstrap does.

Do you know any way to do it? 

Thanks

**Comment by Loic57** [comment]
Hey, 

Unfortunately my JS skills are 0, that's why I opened a ticket which asks for help. No one gave an answer so step by step I gave up the framework and I'm currently working on a full CSS version, ass Bulma.io does.

Sorry Buddy, I can't help you :/
